name: Frontend Build and Deploy

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v2

      - name: 의존성 설치
        run: npm install

      - name: 프로젝트 빌드
        run: npm run build

      - name: 빌드 결과 업로드
        uses: actions/upload-artifact@v2
        with:
          name: frontend-build
          path: ./dist